### ISSUE TITLE
How to calculate user reward in uniswapv3?

### ISSUE THREAD

**Issue by seniorforblockchain** [seniorforblockchain/Dapp#12]

**Comment by topexpert123** [comment]
Understand the Fee Structure:

Uniswap V3 allows liquidity providers (LPs) to choose different fee tiers (e.g., 0.05%, 0.3%, or 1%). The fees earned depend on the trading volume in the pool.
Determine Liquidity Position:

Each LP has a specific range of prices (the price range where they provide liquidity). The amount of liquidity they provide in that range affects their share of the fees.
